# -*- coding: utf-8 -*-
"""GPT2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o4so3MrQKmgg9YG9wGswip_V2GmURpKk
"""

from transformers import GPT2LMHeadModel
model_hf = GPT2LMHeadModel.from_pretrained("gpt2")

model_dict = model_hf.state_dict()

for k,v in model_dict.items():
  print(k, v.shape)

# GPT2 doesn't use the fixed sin-cos position embedding
model_dict["transformer.wpe.weight"].view(-1)[:20] # position embedding weights

import matplotlib.pyplot as plt
plt.imshow(model_dict["transformer.wpe.weight"])

# look at one of the dims for different pos
plt.plot(model_dict["transformer.wpe.weight"][:,1], label="dim 1")
plt.plot(model_dict["transformer.wpe.weight"][:,100], label="dim 10")
plt.plot(model_dict["transformer.wpe.weight"][:,400], label="dim 400")
# plt.plot(model_dict["transformer.wpe.weight"][:,750], label="dim 750")

plt.legend()
plt.xlabel("Position")
plt.ylabel("Embedding value")
plt.title("Position Embedding Dimensions")
plt.show()

from transformers import pipeline, set_seed
generator = pipeline("text-generation", model="gpt2")

set_seed(36)
generator(
    "Hello, I'm a language model,",
    num_return_sequences=5,
    max_new_tokens=30,
)

"""* Reshuffling of the layer norm i.e., pre-block. The advantage is the gradient flow is smoother
* Additional layer norm before the final linear layer

"""

from dataclasses import dataclass
import math
import torch
import torch.nn as nn
from torch.nn import functional as F
import inspect

@dataclass
class GPTConfig:
  block_size: int = 1024
  vocab_size: int = 50257
  n_layer: int = 12
  n_head: int = 12
  n_embed: int = 768

from matplotlib import use
class CausalSelfAttention(nn.Module):
  def __init__(self, config):
    super().__init__()

    assert config.n_embed % config.n_head == 0

    # this block contains all 3: Q,K,V
    self.c_attn = nn.Linear(config.n_embed, 3 * config.n_embed)

    self.c_proj = nn.Linear(config.n_embed, config.n_embed)
    # Flag for scaling the proj layer by the no. of residual layers
    # this is done to make sure the SD inside residual terms remain close to 1
    self.c_proj.NANOGPT_SCALE_INIT = 1.0

    self.n_head = config.n_head
    self.n_embed = config.n_embed

    self.register_buffer("bias", torch.tril(torch.ones(config.block_size, config.block_size)).view(1,1, config.block_size, config.block_size))

  def forward(self, x):
    B, T, C = x.size() # batch size, context length, embedding dims


    qkv = self.c_attn(x)
    q, k, v = qkv.split(self.n_embed, dim=2)
    k = k.view(B, T, self.n_head, C // self.n_head) # (B, T, nh, hs)
    q = q.view(B, T, self.n_head, C // self.n_head)
    v = v.view(B, T, self.n_head, C // self.n_head)


    # calculate attention
    q = q.transpose(1,2) # (B, nh, T, hs)
    k = k.transpose(1,2) # (B, nh, T, hs)
    v = v.transpose(1,2) # (B, nh, T, hs)

    # why is it q @ k^T
    # att = (q @ k.transpose(-2, -1)) * (1.0 / math.sqrt(k.size(-1)))
    # att = att.masked_fill(self.bias[:,:,:T,:T] == 0, float('-inf'))
    # att = F.softmax(att, dim=-1)
    # y = att @ v

    # flash attention
    y = F.scaled_dot_product_attention(q, k, v, is_causal=True)

    # concatenate
    y = y.transpose(1,2).contiguous().view(B, T, C)
    y = self.c_proj(y)

    return y

class MLP(nn.Module):
  def __init__(self, config):
    super().__init__()
    self.c_fc = nn.Linear(config.n_embed, 4 * config.n_embed)
    self.gelu = nn.GELU(approximate='tanh')
    self.c_proj = nn.Linear(4 * config.n_embed, config.n_embed)
    # Flag for scaling the proj layer by the no. of residual layers
    # this is done to make sure the SD inside residual terms remain close to 1
    self.c_proj.NANOGPT_SCALE_INIT = 1.0

  def forward(self, x):
    x = self.c_fc(x)
    x = self.gelu(x)
    x = self.c_proj(x)
    return x

class Block(nn.Module):
  def __init__(self, config):
    super().__init__()
    self.ln_1 = nn.LayerNorm(config.n_embed)
    self.attn = CausalSelfAttention(config)
    self.ln_2 = nn.LayerNorm(config.n_embed)
    self.mlp = MLP(config)

  def forward(self,x):
    x = x + self.attn(self.ln_1(x))
    x = x + self.mlp(self.ln_2(x))

    return x

class GPT(nn.Module):
  def __init__(self, config):
    super().__init__()
    self.config = config

    self.transformer = nn.ModuleDict(dict(
        wte = nn.Embedding(config.vocab_size, config.n_embed),
        wpe = nn.Embedding(config.block_size, config.n_embed),
        h = nn.ModuleList([Block(config) for _ in range(config.n_layer)]),
        ln_f = nn.LayerNorm(config.n_embed),
    ))
    self.lm_head = nn.Linear(config.n_embed, config.vocab_size, bias=False)

    # weight sharing
    self.transformer.wte.weight = self.lm_head.weight

    # weights initialization
    self.apply(self._init_weights)

  def _init_weights(self, module):
    if isinstance(module, nn.Linear):
      std = 0.02
      if hasattr(module, 'NANOGPT_SCALE_INIT'):
        std *= (2*self.config.n_layer) ** (-0.5)
      torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)
      if module.bias is not None:
        torch.nn.init.zeros_(module.bias)

    elif isinstance(module, nn.Embedding):
      torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)


  def forward(self, idx, targets=None):

    B, T = idx.shape
    assert T <= self.config.block_size, f"Cannot forward sequence of length {T} and block size {B}"

    pos = torch.arange(0, T, dtype=torch.long, device=idx.device)
    tok_emb = self.transformer.wte(idx) # (B,T,n_embed)
    pos_emb = self.transformer.wpe(pos) # (T,n_embed)

    x = tok_emb + pos_emb
    for block in self.transformer.h:
      x = block(x)

    x = self.transformer.ln_f(x)
    logits = self.lm_head(x) # (B,T,vocab_size)

    loss = None

    if targets is not None:
      loss = F.cross_entropy(logits.view(-1, logits.size(-1)), targets.view(-1)) # (B*T, vocab_size)

    return logits, loss


  @classmethod
  def from_pretrained(cls, model_name):
    """Load pretrained GPT-2 model weights from huggingface"""

    assert model_name in {'gpt2', 'gpt2-medium', 'gpt2-large', 'gpt2-xl'}

    config_args = {
        'gpt2': dict(n_layer=12, n_head=12, n_embed=768),
        'gpt2-medium': dict(n_layer=24, n_head=16, n_embed=1024),
        'gpt2-large': dict(n_layer=36, n_head=20, n_embed=1280),
        'gpt2-xl': dict(n_layer=48, n_head=25, n_embed=1600)
    }[model_name]

    config_args['block_size'] = 1024
    config_args['vocab_size'] = 50257

    config = GPTConfig(**config_args)
    model = GPT(config)

    sd = model.state_dict()
    sd_keys = sd.keys()
    # why are we discarding this
    sd_keys = [k for k in sd_keys if not k.endswith('.attn.bias')]


    model_hf = GPT2LMHeadModel.from_pretrained(model_name)
    sd_hf = model_hf.state_dict()
    sd_keys_hf = sd_hf.keys()

    # why is this ignored
    sd_keys_hf = [k for k in sd_keys_hf if not k.endswith('.attn.masked_bias')]
    sd_keys_hf = [k for k in sd_keys_hf if not k.endswith('.attn.bias')]

    # weigths that needs to be transposed since the original TF had a conv1D which is not used here
    # but is this converted to the pytorch code by HF?
    transposed = ['attn.c_attn.weight', 'attn.c_proj.weight', 'mlp.c_fc.weight', 'mlp.c_proj.weight']

    assert len(sd_keys_hf) == len(sd_keys), f"mismatched keys: {len(sd_keys_hf)} vs {len(sd_keys)}"

    from tabulate import tabulate

    # Collect all unique keys
    all_keys = sorted(set(sd_hf.keys()) | set(sd.keys()))

    rows = []

    for k in all_keys:
        shape_hf = tuple(sd_hf[k].shape) if k in sd_hf else None
        shape_sd = tuple(sd[k].shape) if k in sd else None
        rows.append([k, shape_hf, shape_sd])

    # Print comparison table
    print(tabulate(rows, headers=["Key", "HF Shape", "SD Shape"], tablefmt="grid"))

    # Separate unmatched keys
    only_hf = sorted(set(sd_hf.keys()) - set(sd.keys()))
    only_sd = sorted(set(sd.keys()) - set(sd_hf.keys()))

    print("\nKeys only in HuggingFace dict:")
    for k in only_hf:
        print(k, tuple(sd_hf[k].shape))

    print("\nKeys only in Current model dict:")
    for k in only_sd:
        print(k, tuple(sd[k].shape))

    for k in sd_keys_hf:

      # for transposed ones copy the weights after transpose
      if any(k.endswith(w) for w in transposed):
        assert sd_hf[k].shape[::-1] == sd[k].shape
        with torch.no_grad():
          sd[k].copy_(sd_hf[k].t())

      else:
        assert sd_hf[k].shape == sd[k].shape
        with torch.no_grad():
          sd[k].copy_(sd_hf[k])

    return model


  def configure_optimizers(self, weight_decay, learning_rate, device):

    # get all the params that reqquire gradient
    param_dict = {pn: p for pn, p in self.named_parameters()}
    param_dict = {pn: p for pn, p in param_dict.items() if p.requires_grad}

    # weight decay is applied only to params that are related to transformations
    # and not bias terms or layer norms
    decay_params = [p for n, p in param_dict.items() if p.dim() >= 2]
    nodecay_params = [p for n, p in param_dict.items() if p.dim() < 2]

    optim_groups = [
        {'params': decay_params, 'weight_decay': weight_decay},
        {'params': nodecay_params, 'weight_decay': 0.0}
    ]

    # count of params for our reference
    num_decay_params = sum(p.numel() for p in decay_params)
    num_nodecay_params = sum(p.numel() for p in nodecay_params)

    print(f"num decayed parameter tensors: {len(decay_params)} with {num_decay_params} parameters")
    print(f"num non-decayed parameter tensors: {len(nodecay_params)} with {num_nodecay_params} parameters")

    # adamw has fused version which runs faster on GPU
    fused_available = 'fused' in inspect.signature(torch.optim.AdamW).parameters

    use_fused = fused_available and 'cuda' in device
    print(f"using fused adamw: {use_fused}")
    optimizer = torch.optim.AdamW(optim_groups, lr=learning_rate, betas=(0.9, 0.95), eps=1e-8, fused=use_fused)

    return optimizer

num_return_sequences = 5
max_length = 30

# model = GPT.from_pretrained('gpt2')
model = GPT(GPTConfig) # randomly initialized model
model.eval()
# model.to('cuda')

import tiktoken
enc = tiktoken.get_encoding('gpt2')
tokens = enc.encode("Hello, I am language model")
tokens = torch.tensor(tokens, dtype=torch.long)
tokens = tokens.unsqueeze(0).repeat(num_return_sequences, 1)

torch.manual_seed(36)
x = tokens
# x = torch.zeros((5,1), dtype=torch.long)
while x.size(1) < max_length:
  with torch.no_grad():
    logits, _ = model(x)
    logits = logits[:,-1,:]

    probs = F.softmax(logits, -1)

    topk_probs, topk_indices = torch.topk(probs, 50, dim=-1)
    ix = torch.multinomial(topk_probs,1)

    x_new = torch.gather(topk_indices, -1, ix)
    x = torch.cat((x, x_new), axis=1)



for i in range(num_return_sequences):
  tokens = x[i, :max_length].tolist()
  decoded = enc.decode(tokens)
  print(decoded)
  print('-'*50)

import tiktoken

!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt


class DataLoaderLite:
  def __init__(self, B, T):
    self.B = B
    self.T = T

    with open('input.txt', 'r') as f:
      text = f.read()

    enc = tiktoken.get_encoding('gpt2')
    tokens = enc.encode(text)
    self.tokens = torch.tensor(tokens, dtype=torch.long)
    print(f"Total tokens: {len(self.tokens)}")
    print(f"1 epoch = {len(self.tokens)// (B*T)} batches")

    self.current_pos = 0

  def sample_batch(self):
    B, T = self.B, self.T
    buf = self.tokens[self.current_pos : self.current_pos+B*T+1]
    x = buf[:-1].view(B,T)
    y = buf[1:].view(B,T)
    self.current_pos += B*T

    # reset the current pos if it goes out of bounds
    if self.current_pos >= len(self.tokens) - (B*T+1) :
      self.current_pos = 0

    return x, y

import torch

if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    try:
        import torch_xla.core.xla_model as xm
        device = xm.xla_device()
    except:
        device = torch.device("cpu")


print(device)

# learning rate decay

# cosine deacy with warmup
# for inital steps the lr is incereased linearly
# then cosine decay (1+cos(pi*decay_ratio)*0.5 is applied to lr
# the decay ratio of current decay step and no. of decay steps


max_lr = 3e-4
min_lr = max_lr * 0.1
warmup_steps = 10
max_steps = 50

def get_lr(itr):
  if itr < warmup_steps:
    return max_lr * (itr+1)/ warmup_steps

  if itr > max_steps:
    return min_lr

  decay_ratio = (itr - warmup_steps) / (max_steps - warmup_steps)
  assert 0 <= decay_ratio <= 1

  coeff = 0.5 * (1.0 + math.cos(math.pi * decay_ratio)) # 1 --> 0

  return min_lr + coeff * (max_lr - min_lr)

# import tiktoken

# !wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
# with open('input.txt', 'r') as f:
  # text = f.read()
# import tiktoken
# enc = tiktoken.get_encoding('gpt2')
# tokens = enc.encode(data)
# # print(tokens[:100])
# B, T = 4, 32
# buf = torch.tensor(tokens[:B*T+1])
# x = buf[:-1].view(B,T)
# y = buf[1:].view(B,T)

# model = GPT(GPTConfig) # randomly initialized model

# logits, loss = model(x,y)
# print(f"Initial loss: {loss}")

import time

# device = torch.device("cpu")

model = GPT(GPTConfig(vocab_size=50304)) # randomly initialized model
model.to(device)
model = torch.compile(model)
iterations = 100

data_loader = DataLoaderLite(B=16, T=256)

# optimizer = torch.optim.AdamW(model.parameters(), lr=3e-4, betas=(0.9, 0.95), eps=1e-8)

# creating optimizer inside the model
optimizer = model.configure_optimizers(weight_decay=0.1, learning_rate=6e-4, device=device)

for step in range(iterations):
  t0 = time.time()
  x,y = data_loader.sample_batch()
  x = x.to(device)
  y = y.to(device)
  optimizer.zero_grad()
  # with torch.autocast(device_type='cuda', dtype=torch.float16):
  logits, loss =  model(x,y)

  # import code; code.interact(local=locals())
  loss.backward()

  # norm of all the gradients
  norm = torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)

  lr = get_lr(step)
  for param_group in optimizer.param_groups:
    param_group['lr'] = lr

  optimizer.step()

  # torch.cuda.synchronize()
  t1 = time.time()
  dt = (t1 - t0)*1000

  tokens_process = data_loader.B * data_loader.T
  tokens_per_sec = tokens_process / dt

  print(f"Iteration: {step+1 :4d} | loss: {loss.item():.6f} | lr: {lr:.4e} | global norm: {norm: .4f} | dt: {dt:.2f}ms | tok/sec: {tokens_per_sec:.2f}")

#
# model.to('cuda')

# with grad accumulation
import time

total_batch_size = 524288
B = 16
T = 256

assert total_batch_size % (B*T) == 0, "ensure total_batch_size is divisible by B*T"

grad_accum_steps = total_batch_size // (B*T)
print(f"Total desired batch size: {total_batch_size}")
print(f" Gradient accumulation steps: {grad_accum_steps}")


iterations = total_batch_size // (B*T)

# device = torch.device("cpu")

model = GPT(GPTConfig(vocab_size=50304)) # randomly initialized model
model.to(device)
model = torch.compile(model)
iterations = 100

data_loader = DataLoaderLite(B, T)

# optimizer = torch.optim.AdamW(model.parameters(), lr=3e-4, betas=(0.9, 0.95), eps=1e-8)

# creating optimizer inside the model
optimizer = model.configure_optimizers(weight_decay=0.1, learning_rate=6e-4, device=device)

for step in range(iterations):
  t0 = time.time()
  optimizer.zero_grad()

  loss_accum = 0
  for mico_step in range(grad_accum_steps):
    x,y = data_loader.sample_batch()
    x = x.to(device)
    y = y.to(device)

    # with torch.autocast(device_type='cuda', dtype=torch.float16):
    logits, loss =  model(x,y)
    # since we want the mean value of loss over the entire batch for
    # which gradients are applied scale the loss value
    loss = loss / grad_accum_steps

    loss_accum += loss.detach()

    # import code; code.interact(local=locals())
    loss.backward() # gets accumulated for grad_accum_steps

  # norm of all the gradients
  norm = torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)

  lr = get_lr(step)
  for param_group in optimizer.param_groups:
    param_group['lr'] = lr

  optimizer.step()

  # torch.cuda.synchronize()
  t1 = time.time()
  dt = (t1 - t0)*1000

  tokens_process = data_loader.B * data_loader.T * grad_accum_steps
  tokens_per_sec = tokens_process / dt

  print(f"Iteration: {step+1 :4d} | loss: {loss_accum.item():.6f} | lr: {lr:.4e} | global norm: {norm: .4f} | dt: {dt:.2f}ms | tok/sec: {tokens_per_sec:.2f}")

#
# model.to('cuda')

import torch
import gc

try:
    del model
    del optimizer
    del loss
    del outputs
    del inputs
except:
    pass

gc.collect()
torch.cuda.empty_cache()
torch.cuda.ipc_collect()

import torch
print(torch.cuda.memory_summary())

"""1. What does model.to(device) actually do

* autocast - Converts some of the operations to float16 fastening the training and some layers ops use the float32
* torch.compile - creates optimized computation graph. Sees the entire code and tries to dynamically fuse the operations for execution on GPU. This avoids the data transfer between the GPU kernels i.e., Streaming Multiprocessors (SMs) and High Bandwidth Memory (HBM)
* Memory Hierarchy:
  * Speed to read and write: SRAM >> HBM >> DRAM
  * Memory size: SRAM << HBM << DRAM

* The memory inside SMs (SRAM) are the L1 and L2 caches
*  Read about FlashAttention in detail
    * Uses online-softmax trick
    * The block of $V {\rm softmax}(QK^T/\sqrt{d})$ is done insider the SM itself
    * Even though it uses more flops but is faster since there is no data transfer with HBM

* Since the matix multiplication is split across kernels its better to have multiples of 2^x as the matrix dims. For example here the vocab_size

### Distributed Data Parallel
"""